name: Ubuntu

on:
  push:
    branches:
      - master
      - wip
  pull_request:
    branches:
      - master

jobs:
  build_gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "initialize sub modules"
        run: git submodule update --init --recursive
      - name: "install dependencies"
        run: |
          set -ex
          cat /etc/apt/sources.list
          sudo apt -q update
          sudo apt install -y "g++-9"
      - name: "create build directory"
        run: mkdir build
      - name: "cmake"
        run: |
          cd build && cmake .. \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=g++-9
      - name: "build"
        run: cmake --build build/ -- -j3
      - name: "test"
        run: ./build/test_dim
  build_clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "initialize sub modules"
        run: git submodule update --init --recursive
      - name: "install dependencies"
        run: |
          set -ex
          cat /etc/apt/sources.list
          sudo apt -q update
          sudo apt install -y "clang++-9"
      - name: "create build directory"
        run: mkdir build
      - name: "cmake"
        run: |
          cd build && cmake .. \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=clang++-9
      - name: "build"
        run: cmake --build build/ -- -j3
      - name: "test"
        run: ./build/test_dim
